#!/bin/bash
set -e

# Generates a GPG Ed25519 signing key for Dispatcharr manifest signing.
# Outputs:
#   dispatcharr-plugins.pub  - public key to bundle in the Dispatcharr app
#   dispatcharr-plugins.key  - private key to set as the GPG_PRIVATE_KEY repo secret
#   dispatcharr-plugins.pass - passphrase to set as the GPG_PASSPHRASE repo secret

EMAIL="plugins@dispatcharr.tv"
NAME="Dispatcharr Plugin Repo"
PASSPHRASE=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 128)
KEYS_DIR="$(cd "$(dirname "$0")" && pwd)"

# Use an isolated temporary keyring so the user's main keyring is never touched
GNUPGHOME=$(mktemp -d)
export GNUPGHOME
trap 'rm -rf "$GNUPGHOME"' EXIT
chmod 700 "$GNUPGHOME"

echo "Generating GPG signing key..."
echo "  Identity : $NAME <$EMAIL>"
echo "  Algorithm: Ed25519"
echo "  Passphrase: $PASSPHRASE"
echo ""

gpg --batch --pinentry-mode loopback --passphrase "$PASSPHRASE" --gen-key <<EOF
Key-Type: EdDSA
Key-Curve: ed25519
Key-Usage: sign
Name-Real: ${NAME}
Name-Comment: dispatcharr-autogenerated
Name-Email: ${EMAIL}
Expire-Date: 0
%commit
EOF

FPR=$(gpg --list-secret-keys --with-colons 2>/dev/null | awk -F: '/^fpr/{print $10}' | head -1)

rm -f "$KEYS_DIR/dispatcharr-plugins.key" "$KEYS_DIR/dispatcharr-plugins.pub" "$KEYS_DIR/dispatcharr-plugins.pass"
gpg --batch --pinentry-mode loopback --passphrase "$PASSPHRASE" --armor --export-secret-keys "$FPR" > "$KEYS_DIR/dispatcharr-plugins.key"
gpg --armor --export "$FPR" > "$KEYS_DIR/dispatcharr-plugins.pub"
echo "$PASSPHRASE" > "$KEYS_DIR/dispatcharr-plugins.pass"

echo ""
gpg --list-secret-keys --keyid-format LONG

echo ""
echo "Files written:"
echo "  dispatcharr-plugins.pub   → bundle into Dispatcharr app (included in this repo)"
echo "  dispatcharr-plugins.key   → set as GPG_PRIVATE_KEY repo secret (ignored by .gitignore)"
echo "  dispatcharr-plugins.pass  → set as GPG_PASSPHRASE repo secret (ignored by .gitignore)"
echo ""
